/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author NuevoUser
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    
    private final String placeholderContra = "Contraseña";
    private final String placeholderCorreo = " Correo Electrónico";
    
    public IniciarSesion() {
        initComponents();
        //setLocationRelativeTo(null);
        this.lblIncorrectos.setVisible(false);
        this.txtCorreo1.setText(placeholderCorreo);
        this.txtPassword.setText(placeholderContra);
        this.txtPassword.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        txtCorreo1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnOlvidaste = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnOtroRegistro = new javax.swing.JButton();
        lblIncorrectos = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(130, 195, 199));

        jPanel2.setBackground(new java.awt.Color(6, 135, 156));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setBackground(new java.awt.Color(233, 186, 116));
        btnIniciarSesion.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(32, 58, 57));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, -1));

        txtCorreo1.setBackground(new java.awt.Color(140, 214, 218));
        txtCorreo1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCorreo1.setForeground(new java.awt.Color(32, 58, 57));
        txtCorreo1.setText("Correo Electrónico");
        txtCorreo1.setBorder(null);
        txtCorreo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreo1FocusLost(evt);
            }
        });
        jPanel2.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, 20));

        txtPassword.setBackground(new java.awt.Color(140, 214, 218));
        txtPassword.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(32, 58, 57));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 186, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar Sesión");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 30));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 206, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido de nuevo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 160, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/correoEl.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 230, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/contraseña.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/botonVerificar.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 50));

        btnOlvidaste.setBackground(new java.awt.Color(6, 135, 156));
        btnOlvidaste.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        btnOlvidaste.setForeground(new java.awt.Color(140, 214, 218));
        btnOlvidaste.setText("<html><u><b>¿Olvidaste tu contraseña?</u></b>");
        btnOlvidaste.setBorder(null);
        btnOlvidaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnOlvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(140, 214, 218));
        jLabel6.setText("¿No tienes cuenta?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnOtroRegistro.setBackground(new java.awt.Color(6, 135, 156));
        btnOtroRegistro.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        btnOtroRegistro.setForeground(new java.awt.Color(140, 214, 218));
        btnOtroRegistro.setText("<html><u><b>Registrarse");
        btnOtroRegistro.setBorder(null);
        btnOtroRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnOtroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 70, 30));

        lblIncorrectos.setFont(new java.awt.Font("Montserrat Light", 0, 10)); // NOI18N
        lblIncorrectos.setForeground(new java.awt.Color(153, 0, 0));
        lblIncorrectos.setText("*Correo o contraseña incorrectos");
        jPanel2.add(lblIncorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreo1FocusGained
        if(this.txtCorreo1.getText().equals(placeholderCorreo)){
             this.txtCorreo1.setText("");
         }
    }//GEN-LAST:event_txtCorreo1FocusGained

    private void txtCorreo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreo1FocusLost
        if(this.txtCorreo1.getText().isEmpty()){
            this.txtCorreo1.setText(placeholderCorreo);
        }
    }//GEN-LAST:event_txtCorreo1FocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(String.valueOf(this.txtPassword.getPassword()).equals(placeholderContra)){
           this.txtPassword.setText("");
           this.txtPassword.setEchoChar('·');
       }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(String.valueOf(this.txtPassword.getPassword()).isEmpty()){
           this.txtPassword.setText(placeholderContra);
           this.txtPassword.setEchoChar((char) 0);
       }
    }//GEN-LAST:event_txtPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    public JTextField getTxtCorreo1() {
        return txtCorreo1;
    }

    public void setTxtCorreo1(JTextField txtCorreo1) {
        this.txtCorreo1 = txtCorreo1;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JButton getBtnIniciarSesion() {
        return btnIniciarSesion;
    }

    public void setBtnIniciarSesion(JButton btnIniciarSesion) {
        this.btnIniciarSesion = btnIniciarSesion;
    }

    public JButton getBtnOlvidaste() {
        return btnOlvidaste;
    }

    public void setBtnOlvidaste(JButton btnOlvidaste) {
        this.btnOlvidaste = btnOlvidaste;
    }

    public JButton getBtnOtroRegistro() {
        return btnOtroRegistro;
    }

    public void setBtnOtroRegistro(JButton btnOtroRegistro) {
        this.btnOtroRegistro = btnOtroRegistro;
    }

    public JLabel getLblIncorrectos() {
        return lblIncorrectos;
    }

    public void setLblIncorrectos(JLabel lblIncorrectos) {
        this.lblIncorrectos = lblIncorrectos;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnOlvidaste;
    private javax.swing.JButton btnOtroRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblIncorrectos;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
