/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author NuevoUser
 */
public class NuevaContra extends javax.swing.JFrame {

    private final String placeholderContra = "Contraseña";
    private final String placeholderContra1 = "Confirmar Contraseña";
    private final String placeholderCorreo = "Correo Electrónico";
    
    public NuevaContra() {
        initComponents();
        
        this.txtCorreoo.setText(placeholderCorreo);
        
        
        this.lblNoCoinciden.setVisible(false);
        this.lblNoRegistrado1.setVisible(false);
        this.btnListo.setVisible(false);
        this.txtContras.setVisible(false);
        this.txtContrasVer.setVisible(false);
        this.lblimagen.setVisible(false);
        this.lblImagen2.setVisible(false);
        this.lblImagen3.setVisible(false);
        this.lblIngresa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCambiar = new javax.swing.JButton();
        txtCorreoo = new javax.swing.JTextField();
        txtContrasVer = new javax.swing.JPasswordField();
        txtContras = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        btnListo = new javax.swing.JButton();
        lblImagen3 = new javax.swing.JLabel();
        lblIngresa = new javax.swing.JLabel();
        lblNoCoinciden = new javax.swing.JLabel();
        lblNoRegistrado1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 135, 156));

        jPanel2.setBackground(new java.awt.Color(6, 135, 156));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCambiar.setBackground(new java.awt.Color(233, 186, 116));
        btnCambiar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(32, 58, 57));
        btnCambiar.setText("Cambiar contraseña");
        btnCambiar.setBorder(null);
        btnCambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 30));

        txtCorreoo.setBackground(new java.awt.Color(140, 214, 218));
        txtCorreoo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCorreoo.setForeground(new java.awt.Color(32, 58, 57));
        txtCorreoo.setText("Correo Electrónico");
        txtCorreoo.setBorder(null);
        txtCorreoo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreooFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreooFocusLost(evt);
            }
        });
        txtCorreoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreooActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 20));

        txtContrasVer.setBackground(new java.awt.Color(140, 214, 218));
        txtContrasVer.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtContrasVer.setForeground(new java.awt.Color(32, 58, 57));
        txtContrasVer.setText("jPasswordField1");
        txtContrasVer.setBorder(null);
        txtContrasVer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasVerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasVerFocusLost(evt);
            }
        });
        jPanel2.add(txtContrasVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 150, 20));

        txtContras.setBackground(new java.awt.Color(140, 214, 218));
        txtContras.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtContras.setForeground(new java.awt.Color(32, 58, 57));
        txtContras.setText("jPasswordField1");
        txtContras.setBorder(null);
        txtContras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasFocusLost(evt);
            }
        });
        jPanel2.add(txtContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 150, 20));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 186, 116));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recuperar Contraseña");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 40));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 206, 204));
        jLabel2.setText("Cambia tu contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 206, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresa tu correo para cambiar la contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/correoEl.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/botonVerificar.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, 60));

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/contraseña.png"))); // NOI18N
        jPanel2.add(lblImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, 50));

        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/contraseña.png"))); // NOI18N
        jPanel2.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 230, 50));

        btnListo.setBackground(new java.awt.Color(233, 186, 116));
        btnListo.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnListo.setForeground(new java.awt.Color(32, 58, 57));
        btnListo.setText("Listo");
        btnListo.setBorder(null);
        btnListo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jPanel2.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 160, 30));

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/botonVerificar.png"))); // NOI18N
        jPanel2.add(lblImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 200, 60));

        lblIngresa.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblIngresa.setForeground(new java.awt.Color(150, 206, 204));
        lblIngresa.setText("Ingresa tu nueva contraseña");
        jPanel2.add(lblIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        lblNoCoinciden.setFont(new java.awt.Font("Montserrat Light", 0, 10)); // NOI18N
        lblNoCoinciden.setForeground(new java.awt.Color(204, 0, 0));
        lblNoCoinciden.setText("Las contraseñas no coinciden");
        jPanel2.add(lblNoCoinciden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 20));

        lblNoRegistrado1.setFont(new java.awt.Font("Montserrat Light", 0, 10)); // NOI18N
        lblNoRegistrado1.setForeground(new java.awt.Color(204, 0, 0));
        lblNoRegistrado1.setText("* Correo no registrado");
        jPanel2.add(lblNoRegistrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 40));

        btnRegresar.setBackground(new java.awt.Color(6, 135, 156));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/flechaFO.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListoActionPerformed

    private void txtCorreooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreooActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
      
        
        
        this.txtContras.setEchoChar((char) 0);
        this.txtContras.setText(placeholderContra);
        this.txtContrasVer.setEchoChar((char) 0);
        this.txtContrasVer.setText(placeholderContra1);
        
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void txtCorreooFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreooFocusGained
        if(this.txtCorreoo.getText().equals(placeholderCorreo)){
             this.txtCorreoo.setText("");
         }
    }//GEN-LAST:event_txtCorreooFocusGained

    private void txtCorreooFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreooFocusLost
        if(this.txtCorreoo.getText().isEmpty()){
            this.txtCorreoo.setText(placeholderCorreo);
        }
    }//GEN-LAST:event_txtCorreooFocusLost

    private void txtContrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasFocusGained
        if(String.valueOf(this.txtContras.getPassword()).equals(placeholderContra)){
           this.txtContras.setText("");
           this.txtContras.setEchoChar('·');
       }
    }//GEN-LAST:event_txtContrasFocusGained

    private void txtContrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasFocusLost
        if(String.valueOf(this.txtContras.getPassword()).isEmpty()){
           this.txtContras.setText(placeholderContra);
           this.txtContras.setEchoChar((char) 0);
       }
    }//GEN-LAST:event_txtContrasFocusLost

    private void txtContrasVerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasVerFocusGained
        if(String.valueOf(this.txtContrasVer.getPassword()).equals(placeholderContra1)){
           this.txtContrasVer.setText("");
           this.txtContrasVer.setEchoChar('·');
       }
    }//GEN-LAST:event_txtContrasVerFocusGained

    private void txtContrasVerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasVerFocusLost
       if(String.valueOf(this.txtContrasVer.getPassword()).isEmpty()){
           this.txtContrasVer.setText(placeholderContra1);
           this.txtContrasVer.setEchoChar((char) 0);
       }
    }//GEN-LAST:event_txtContrasVerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaContra().setVisible(true);
            }
        });
    }

    public JButton getBtnCambiar() {
        return btnCambiar;
    }

    public void setBtnCambiar(JButton btnCambiar) {
        this.btnCambiar = btnCambiar;
    }

    public JButton getBtnListo() {
        return btnListo;
    }

    public void setBtnListo(JButton btnListo) {
        this.btnListo = btnListo;
    }

    public JLabel getLblImagen2() {
        return lblImagen2;
    }

    public void setLblImagen2(JLabel lblImagen2) {
        this.lblImagen2 = lblImagen2;
    }

    public JLabel getLblImagen3() {
        return lblImagen3;
    }

    public void setLblImagen3(JLabel lblImagen3) {
        this.lblImagen3 = lblImagen3;
    }

    public JLabel getLblIngresa() {
        return lblIngresa;
    }

    public void setLblIngresa(JLabel lblIngresa) {
        this.lblIngresa = lblIngresa;
    }

    public JLabel getLblimagen() {
        return lblimagen;
    }

    public void setLblimagen(JLabel lblimagen) {
        this.lblimagen = lblimagen;
    }

    public JPasswordField getTxtContras() {
        return txtContras;
    }

    public void setTxtContras(JPasswordField txtContras) {
        this.txtContras = txtContras;
    }

    public JPasswordField getTxtContrasVer() {
        return txtContrasVer;
    }

    public void setTxtContrasVer(JPasswordField txtContrasVer) {
        this.txtContrasVer = txtContrasVer;
    }

    public JTextField getTxtCorreoo() {
        return txtCorreoo;
    }

    public void setTxtCorreoo(JTextField txtCorreoo) {
        this.txtCorreoo = txtCorreoo;
    }

    public JLabel getLblNoCoinciden() {
        return lblNoCoinciden;
    }

    public void setLblNoCoinciden(JLabel lblNoCoinciden) {
        this.lblNoCoinciden = lblNoCoinciden;
    }

    public JLabel getLblNoRegistrado1() {
        return lblNoRegistrado1;
    }

    public void setLblNoRegistrado1(JLabel lblNoRegistrado1) {
        this.lblNoRegistrado1 = lblNoRegistrado1;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblIngresa;
    private javax.swing.JLabel lblNoCoinciden;
    private javax.swing.JLabel lblNoRegistrado1;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JPasswordField txtContras;
    private javax.swing.JPasswordField txtContrasVer;
    private javax.swing.JTextField txtCorreoo;
    // End of variables declaration//GEN-END:variables
}
