/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author NuevoUser
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    private final String placeholderContra = "Contraseña";
    private final String placeholderNombre = "Nombre Completo";
    private final String placeholderCorreo = "Correo Electrónico";
    
    public Registro() {
        initComponents();
        
        this.btnGuardar.setEnabled(false);
        this.txtCorreo.setText(placeholderCorreo);
        this.txtNombre.setText(placeholderNombre);
        this.txtContrasenia.setText(placeholderContra);
        this.txtContrasenia.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSesion = new javax.swing.JLabel();
        chkPoliticas = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        btnOtraSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 135, 156));

        jPanel3.setBackground(new java.awt.Color(6, 135, 156));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(140, 214, 218));
        txtNombre.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(32, 58, 57));
        txtNombre.setText("Nombre Completo");
        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 180, 20));

        txtCorreo.setBackground(new java.awt.Color(140, 214, 218));
        txtCorreo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(32, 58, 57));
        txtCorreo.setText("Correo Electrónico");
        txtCorreo.setBorder(null);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 180, 20));

        txtContrasenia.setBackground(new java.awt.Color(140, 214, 218));
        txtContrasenia.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(32, 58, 57));
        txtContrasenia.setText("Contraseña");
        txtContrasenia.setBorder(null);
        txtContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusLost(evt);
            }
        });
        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        jPanel3.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 20));

        btnGuardar.setBackground(new java.awt.Color(233, 186, 116));
        btnGuardar.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(32, 58, 57));
        btnGuardar.setText("Crear Cuenta");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 20));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 39)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 186, 116));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 172, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/nombre1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 51));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 206, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crea una cuenta nueva");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 12));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/botonA.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/correoEl.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/aplicaciones.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 240, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/contraseña.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 51));

        lblSesion.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        lblSesion.setForeground(new java.awt.Color(140, 214, 218));
        lblSesion.setText("¿Ya tienes una cuenta?");
        lblSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 110, 10));

        chkPoliticas.setBackground(new java.awt.Color(6, 135, 156));
        chkPoliticas.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        chkPoliticas.setForeground(new java.awt.Color(255, 255, 255));
        chkPoliticas.setText("<html><p>Estoy de acuerdo con las <u>Politicas y Condiciones <br><u>de privacidad</u></p></html>");
        chkPoliticas.setBorder(null);
        chkPoliticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chkPoliticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPoliticasActionPerformed(evt);
            }
        });
        jPanel3.add(chkPoliticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-------------------- O continua con ----------------------");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, 10));

        btnOtraSesion.setBackground(new java.awt.Color(6, 135, 156));
        btnOtraSesion.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        btnOtraSesion.setForeground(new java.awt.Color(140, 214, 218));
        btnOtraSesion.setText("<html><u><b>Iniciar sesión</b></u>");
        btnOtraSesion.setBorder(null);
        btnOtraSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOtraSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraSesionActionPerformed(evt);
            }
        });
        jPanel3.add(btnOtraSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 90, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
       // this.lblCorreo.setVisible(false);
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void chkPoliticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPoliticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPoliticasActionPerformed

    private void txtContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusGained
       if(String.valueOf(this.txtContrasenia.getPassword()).equals(placeholderContra)){
           this.txtContrasenia.setText("");
           this.txtContrasenia.setEchoChar('·');
       }
    }//GEN-LAST:event_txtContraseniaFocusGained

    private void txtContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusLost
       if(String.valueOf(this.txtContrasenia.getPassword()).isEmpty()){
           this.txtContrasenia.setText(placeholderContra);
           this.txtContrasenia.setEchoChar((char) 0);
       }
    }//GEN-LAST:event_txtContraseniaFocusLost

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
         if(this.txtNombre.getText().equals(placeholderNombre)){
             this.txtNombre.setText("");
         }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if(this.txtCorreo.getText().equals(placeholderCorreo)){
             this.txtCorreo.setText("");
         }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(this.txtNombre.getText().isEmpty()){
            this.txtNombre.setText(placeholderNombre);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(this.txtCorreo.getText().isEmpty()){
            this.txtCorreo.setText(placeholderCorreo);
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOtraSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtraSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JCheckBox getChkPoliticas() {
        return chkPoliticas;
    }

    public void setChkPoliticas(JCheckBox chkPoliticas) {
        this.chkPoliticas = chkPoliticas;
    }


    public JPasswordField getTxtContrasenia() {
        return txtContrasenia;
    }

    public void setTxtContrasenia(JPasswordField txtContrasenia) {
        this.txtContrasenia = txtContrasenia;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JButton getBtnOtraSesion() {
        return btnOtraSesion;
    }

    public void setBtnOtraSesion(JButton btnOtraSesion) {
        this.btnOtraSesion = btnOtraSesion;
    }

  
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOtraSesion;
    private javax.swing.JCheckBox chkPoliticas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
