/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author NuevoUser
 */
public class Verificacion extends javax.swing.JFrame {

    /**
     * Creates new form Verificacion
     */
    public Verificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVerificar = new javax.swing.JButton();
        txtDigito4 = new javax.swing.JTextField();
        txtDigito1 = new javax.swing.JTextField();
        txtDigito2 = new javax.swing.JTextField();
        txtDigito3 = new javax.swing.JTextField();
        lblVolverInte = new javax.swing.JLabel();
        btnOtroCodigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 135, 156));

        jPanel2.setBackground(new java.awt.Color(6, 135, 156));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerificar.setBackground(new java.awt.Color(233, 186, 116));
        btnVerificar.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(32, 58, 57));
        btnVerificar.setText("Verificar");
        btnVerificar.setAlignmentY(0.0F);
        btnVerificar.setBorder(null);
        btnVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 20));

        txtDigito4.setBackground(new java.awt.Color(140, 214, 218));
        txtDigito4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtDigito4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito4.setBorder(null);
        txtDigito4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigito4ActionPerformed(evt);
            }
        });
        jPanel2.add(txtDigito4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 30, 30));

        txtDigito1.setBackground(new java.awt.Color(140, 214, 218));
        txtDigito1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtDigito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito1.setBorder(null);
        txtDigito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigito1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtDigito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 30, 30));

        txtDigito2.setBackground(new java.awt.Color(140, 214, 218));
        txtDigito2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtDigito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito2.setBorder(null);
        txtDigito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigito2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtDigito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 30, 30));

        txtDigito3.setBackground(new java.awt.Color(140, 214, 218));
        txtDigito3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtDigito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito3.setBorder(null);
        txtDigito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigito3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtDigito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 30, 30));

        lblVolverInte.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        lblVolverInte.setForeground(new java.awt.Color(140, 214, 218));
        lblVolverInte.setText("¿No recibiste un código? ");
        lblVolverInte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverInteMouseClicked(evt);
            }
        });
        jPanel2.add(lblVolverInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 20));

        btnOtroCodigo.setBackground(new java.awt.Color(6, 135, 156));
        btnOtroCodigo.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        btnOtroCodigo.setForeground(new java.awt.Color(140, 214, 218));
        btnOtroCodigo.setText("<html> <u><b>Volver a intentarlo");
        btnOtroCodigo.setBorder(null);
        btnOtroCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnOtroCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, 20));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 186, 116));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Verificación");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 206, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Ingresa el código de verificacion que <br>se te ha enviado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/botonVerificar.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/images/codigo.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void lblVolverInteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverInteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverInteMouseClicked

    private void txtDigito4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigito4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigito4ActionPerformed

    private void txtDigito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigito1ActionPerformed

    private void txtDigito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigito2ActionPerformed

    private void txtDigito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigito3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verificacion().setVisible(true);
            }
        });
    }

    public JButton getBtnVerificar() {
        return btnVerificar;
    }

    public void setBtnVerificar(JButton btnVerificar) {
        this.btnVerificar = btnVerificar;
    }

    public JLabel getLblVolverInte() {
        return lblVolverInte;
    }

    public void setLblVolverInte(JLabel lblVolverInte) {
        this.lblVolverInte = lblVolverInte;
    }

    public JTextField getTxtDigito1() {
        return txtDigito1;
    }

    public void setTxtDigito1(JTextField txtDigito1) {
        this.txtDigito1 = txtDigito1;
    }

    public JTextField getTxtDigito2() {
        return txtDigito2;
    }

    public void setTxtDigito2(JTextField txtDigito2) {
        this.txtDigito2 = txtDigito2;
    }

    public JTextField getTxtDigito3() {
        return txtDigito3;
    }

    public void setTxtDigito3(JTextField txtDigito3) {
        this.txtDigito3 = txtDigito3;
    }

    public JTextField getTxtDigito4() {
        return txtDigito4;
    }

    public void setTxtDigito4(JTextField txtDigito4) {
        this.txtDigito4 = txtDigito4;
    }

    public JButton getBtnOtroCodigo() {
        return btnOtroCodigo;
    }

    public void setBtnOtroCodigo(JButton btnOtroCodigo) {
        this.btnOtroCodigo = btnOtroCodigo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtroCodigo;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblVolverInte;
    private javax.swing.JTextField txtDigito1;
    private javax.swing.JTextField txtDigito2;
    private javax.swing.JTextField txtDigito3;
    private javax.swing.JTextField txtDigito4;
    // End of variables declaration//GEN-END:variables
}
