/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.SwingConstants;

public class config extends javax.swing.JFrame {
       private ImageIcon imagen;
      private Icon icono;
    
    public config() {
        initComponents();
        this.Imagen1("src/vista/image/btn_CallCenter.png");
        this.Imagen2("src/vista/image/btn_Reporte.png");
        this.Imagen3("src/vista/image/btn_EditarP.png");
        this.Imagen4("src/vista/image/btn_ChatA.png");
        this.Imagen5("src/vista/image/btn_CondPoli.png");
        this.Imagen6("src/vista/image/btn_AvisoS.png");
        this.Imagen7("src/vista/image/btnBack.png");
        this.Imagen8("src/vista/image/barra_nav.png");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCondi = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        lblAvisos = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();
        lblNavegacion = new javax.swing.JLabel();
        lblCallC = new javax.swing.JLabel();

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(130, 195, 199));
        jPanel1.setForeground(new java.awt.Color(130, 195, 199));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btnBack.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Configuración");

        lblCondi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_CondPoli.png"))); // NOI18N
        lblCondi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCondi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCondiMouseClicked(evt);
            }
        });

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_EditarP.png"))); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });

        lblReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_Reporte.png"))); // NOI18N
        lblReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReporteMouseClicked(evt);
            }
        });

        lblAvisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_AvisoS.png"))); // NOI18N
        lblAvisos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvisosMouseClicked(evt);
            }
        });

        lblChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_ChatA.png"))); // NOI18N
        lblChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChatMouseClicked(evt);
            }
        });

        lblNavegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/barra_nav.png"))); // NOI18N

        lblCallC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/btn_callCenter.png"))); // NOI18N
        lblCallC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCallC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCallC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCallC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCallCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNavegacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCallC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCondi))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChat)
                            .addComponent(lblReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCallC)
                    .addComponent(lblReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCondi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteMouseClicked
        //  reporte.setVisible(true);
    }//GEN-LAST:event_lblReporteMouseClicked

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        //  perfil.setVisible(true);
    }//GEN-LAST:event_lblEditarMouseClicked

    private void lblChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChatMouseClicked
        // chat.setVisible(true);
    }//GEN-LAST:event_lblChatMouseClicked

    private void lblCondiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCondiMouseClicked
        //vista2.setVisible(true);
    }//GEN-LAST:event_lblCondiMouseClicked

    private void lblAvisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvisosMouseClicked
        // aviso.setVisible(true);
    }//GEN-LAST:event_lblAvisosMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // pantalla anterior
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblCallCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCallCMouseClicked
        // callC.setVisible(true);
    }//GEN-LAST:event_lblCallCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new config().setVisible(true);
            }
        });
    }
    
     private void Imagen1(String ruta){
         this.imagen = new ImageIcon(ruta);
        // Jlabel labelBoton = new Jblabel(icono);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblCallC.getWidth(), this.lblCallC.getHeight(), Image.SCALE_DEFAULT));
         this.lblCallC.setIcon(this.icono);
         this.repaint();
         // labelBoton.setHorizontalAlignment(SwingConstants.CENTER);
          //labelBoton.setCursor(new Cursor(cursor.HAND_CURSOR));
         
         // labelBoton.addMouseListener(new MouseAdapter() {
           // @Override
            //public void mouseClicked(MouseEvent e) {
            
         
        
     }
     
      private void Imagen2(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblReporte.getWidth(), this.lblReporte.getHeight(), Image.SCALE_DEFAULT));
         this.lblReporte.setIcon(this.icono);
         this.repaint();
     }
      
      private void Imagen3(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblEditar.getWidth(), this.lblEditar.getHeight(), Image.SCALE_DEFAULT));
         this.lblEditar.setIcon(this.icono);
         this.repaint();
     }
      private void Imagen4(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblChat.getWidth(), this.lblChat.getHeight(), Image.SCALE_DEFAULT));
         this.lblChat.setIcon(this.icono);
         this.repaint();
     }
      
      private void Imagen5(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblCondi.getWidth(), this.lblCondi.getHeight(), Image.SCALE_DEFAULT));
         this.lblCondi.setIcon(this.icono);
         this.repaint();
     }
      
      private void Imagen6(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblAvisos.getWidth(), this.lblAvisos.getHeight(), Image.SCALE_DEFAULT));
         this.lblAvisos.setIcon(this.icono);
         this.repaint();
     }
      
       private void Imagen7(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblBack.getWidth(), this.lblBack.getHeight(), Image.SCALE_DEFAULT));
         this.lblBack.setIcon(this.icono);
         this.repaint();
     }
       
        private void Imagen8(String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(this.lblNavegacion.getWidth(), this.lblNavegacion.getHeight(), Image.SCALE_DEFAULT));
         this.lblNavegacion.setIcon(this.icono);
         this.repaint();
     }

    public JLabel getLblAvisos() {
        return lblAvisos;
    }

    public void setLblAvisos(JLabel lblAvisos) {
        this.lblAvisos = lblAvisos;
    }

    public JLabel getLblBack() {
        return lblBack;
    }

    public void setLblBack(JLabel lblBack) {
        this.lblBack = lblBack;
    }

    public JLabel getLblCallC() {
        return lblCallC;
    }

    public void setLblCallC(JLabel lblCallC) {
        this.lblCallC = lblCallC;
    }

    public JLabel getLblChat() {
        return lblChat;
    }

    public void setLblChat(JLabel lblChat) {
        this.lblChat = lblChat;
    }

    public JLabel getLblCondi() {
        return lblCondi;
    }

    public void setLblCondi(JLabel lblCondi) {
        this.lblCondi = lblCondi;
    }

    public JLabel getLblEditar() {
        return lblEditar;
    }

    public void setLblEditar(JLabel lblEditar) {
        this.lblEditar = lblEditar;
    }

    public JLabel getLblNavegacion() {
        return lblNavegacion;
    }

    public void setLblNavegacion(JLabel lblNavegacion) {
        this.lblNavegacion = lblNavegacion;
    }

    public JLabel getLblReporte() {
        return lblReporte;
    }

    public void setLblReporte(JLabel lblReporte) {
        this.lblReporte = lblReporte;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvisos;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCallC;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblCondi;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblNavegacion;
    private javax.swing.JLabel lblReporte;
    // End of variables declaration//GEN-END:variables
}
